### ISSUE TITLE
Colliding modules

### ISSUE THREAD

**Issue by WyntherKnight** [OpticalShadows/ACleanModernUI#1]
Hi,

I have 4 modules that visually collides with this one:
1) **ICE UI** makes the top row menu icons on the left (Basic Controls and Select Tokens) differ form the rest of the Icons. 
2) **Custom Hotbar** still places the hotbar to the left and the additional hotbars are still sharp edge squares.
3) **Monk's Token Bar** its action panel is covered by the hotbar since both are now in the lower middle of the screen. (my temp fix is to hide the hotbar)
4) **Dice Tray** is all whited out, the dice icons show when you mouse hover but the math symbols do no appear.

**Comment by OpticalShadows** [comment]
I don't know how much sense it would make to add support for IceUI since it's another UI mod, but I will look at it nonetheless. 
I do have support for monks token bar but I have yet to have it's default position moved since I moved the hotbar. It does have a reposition handle (the brighter section on the left) that lets you drag it around. 
I will look at getting support for the other two modules! Thanks for the feedback!

**Comment by OpticalShadows** [comment]
I have pushed another update that adds support for Dice Tray and Custom Hotbar. Monks Tokenbar is compatible with my UI mod. If for some reason it is under the hotbar, there is a reset position button in the settings for Monks Tokenbar that will bring it to the right side of the Hotbar. Also it can be dragged around like I mentioned in the first reply. I don't see a reason to add support for the Ice UI since it is another UI mod and you would usually only run one of those at a time.

**Comment by WyntherKnight** [comment]
Thank you! If I see other issues, I'll let you know.
